name: build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    environment: automated-release
    runs-on: ubuntu-latest

    env: 
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move release to draft
        run: gh release edit "$TAG_NAME" --draft=true
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Create release archive
        run: |
          zip -r lib.zip . -x '.*' 'node_modules/*' 'src/*' 'spec/*' 'CVClientLA.md'

      - name: Upload production artifacts
        run: |
          gh release upload $TAG_NAME "lib.zip"
          gh release edit $TAG_NAME --draft=false
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}